import = ['~/.config/alacritty/colors.toml']

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.7
dimensions = { columns = 80, lines = 30 }
padding = { x = 10, y = 10 }

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font]
size = 10
